export const TEXT = {
  en: {
    appName: 'SmartCity Companion',
    appSubtitle: 'Chittagong, Bangladesh',
    loginTitle: 'Welcome to Chittagong',
    loginSubtitle: 'Log in to enhance your urban experience.',
    email: 'Email',
    password: 'Password',
    loginBtn: 'Login',
    traffic: 'Traffic',
    fairPrice: 'Fair Price',
    safety: 'Safety',
    trafficTitle: 'Real-time Route & Traffic',
    source: 'Source Location',
    destination: 'Destination Location',
    safetyTitle: 'Safety Zones Map',
    panicBtn: 'SOS / PANIC BUTTON',
    reportUnsafe: 'Report Unsafe Area',
    pricingTitle: 'Fare Price Insights',
    searchProduct: 'Enter Product/Service (e.g., CNG fare, Rice)',
    avgPrice: 'Average Price',
    lowest: 'Lowest',
    highest: 'Highest',
    reportTitle: 'Community Report Submission',
    reportType: 'Select Report Type',
    details: 'Details (what, where, when)',
    uploadPhoto: 'Upload Photo (Optional)',
    submit: 'Submit Report',
    reportSuccess: 'Report Submitted Successfully!',
    home: 'Home',
    reports: 'Reports',
    profile: 'Profile',
    selectType: 'Select Type',
    routeOptions: 'Alternative Routes',
    loading: 'Loading...',
    route1: '1. Fast: via CDA',
    route2: '2. Cheap: via Patenga (local)',
    route3: '3. No Toll: via Kalurghat',
    safeZone: 'Safe Zones',
    unsafeZone: 'Unsafe Zones',
  },
  bn: {
    appName: 'স্মার্ট সিটি সহায়ক',
    appSubtitle: 'চট্টগ্রাম, বাংলাদেশ',
    loginTitle: 'চট্টগ্রামে স্বাগতম',
    loginSubtitle: 'শহুরে অভিজ্ঞতা বাড়াতে লগইন করুন।',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    loginBtn: 'লগইন করুন',
    traffic: 'যানজট',
    fairPrice: 'ন্যায্য মূল্য',
    safety: 'নিরাপত্তা',
    trafficTitle: 'রিয়েল-টাইম রুট ও যানজট',
    source: 'উৎপত্তি স্থান',
    destination: 'গন্তব্য স্থান',
    safetyTitle: 'নিরাপত্তা অঞ্চলের মানচিত্র',
    panicBtn: 'এসওএস / আতঙ্ক বাটন',
    reportUnsafe: 'অনিরাপদ এলাকা জানান',
    pricingTitle: 'গাড়ি ভাড়ার ধারণা',
    searchProduct: 'পণ্য/পরিষেবা লিখুন (যেমন: সিএনজি ভাড়া, চাল)',
    avgPrice: 'গড় মূল্য',
    lowest: 'সর্বনিম্ন',
    highest: 'সর্বোচ্চ',
    reportTitle: 'কমিউনিটি রিপোর্ট জমা দিন',
    reportType: 'রিপোর্টের ধরণ নির্বাচন করুন',
    details: 'বিবরণ (কী, কোথায়, কখন)',
    uploadPhoto: 'ছবি আপলোড করুন (ঐচ্ছিক)',
    submit: 'রিপোর্ট জমা দিন',
    reportSuccess: 'রিপোর্ট সফলভাবে জমা হয়েছে!',
    home: 'হোম',
    reports: 'রিপোর্ট',
    profile: 'প্রোফাইল',
    selectType: 'ধরণ নির্বাচন করুন',
    routeOptions: 'বিকল্প রুট',
    loading: 'লোড হচ্ছে...',
    route1: '১. দ্রুত: সিডিএ হয়ে',
    route2: '২. মনোরম: পতেঙ্গা হয়ে',
    route3: '৩. টোল ছাড়া: কালুরঘাট হয়ে',
    safeZone: 'নিরাপদ এলাকা',
    unsafeZone: 'অনিরাপদ এলাকা',
  },
};
